
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Enemy
{
/// <summary>
/// 怪物表
/// </summary>
public partial class EnemyConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Enemy.EnemyCfg> _dataMap;
    private readonly System.Collections.Generic.List<Enemy.EnemyCfg> _dataList;
    
    public EnemyConfig(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, Enemy.EnemyCfg>(count);
        _dataList = new System.Collections.Generic.List<Enemy.EnemyCfg>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Enemy.EnemyCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.Enemy.EnemyCfg.DeserializeEnemyCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Enemy.EnemyCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<Enemy.EnemyCfg> DataList => _dataList;

    public Enemy.EnemyCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Enemy.EnemyCfg Get(int key) => _dataMap[key];
    public Enemy.EnemyCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

