
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Enemy
{
public sealed partial class EnemyCfg : Luban.BeanBase
{
    public EnemyCfg(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["hp"].IsNumber) { throw new SerializationException(); }  Hp = _buf["hp"]; }
        { if(!_buf["entityId"].IsNumber) { throw new SerializationException(); }  EntityId = _buf["entityId"]; }
    }

    public static EnemyCfg DeserializeEnemyCfg(JSONNode _buf)
    {
        return new Enemy.EnemyCfg(_buf);
    }

    /// <summary>
    /// 怪物id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 最大生命值
    /// </summary>
    public readonly float Hp;
    /// <summary>
    /// 实体id
    /// </summary>
    public readonly int EntityId;
   
    public const int __ID__ = 1404893090;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "hp:" + Hp + ","
        + "entityId:" + EntityId + ","
        + "}";
    }
}
}

