
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    /// <summary>
    /// 音效表
    /// </summary>
    public Audio.AudioConfig AudioConfig {get; }
    /// <summary>
    /// 关卡表
    /// </summary>
    public Level.LevelConfig LevelConfig {get; }
    /// <summary>
    /// 实体表
    /// </summary>
    public Entity.EntityConfig EntityConfig {get; }
    /// <summary>
    /// 怪物表
    /// </summary>
    public Enemy.EnemyConfig EnemyConfig {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        AudioConfig = new Audio.AudioConfig(loader("audio_audioconfig"));
        LevelConfig = new Level.LevelConfig(loader("level_levelconfig"));
        EntityConfig = new Entity.EntityConfig(loader("entity_entityconfig"));
        EnemyConfig = new Enemy.EnemyConfig(loader("enemy_enemyconfig"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        AudioConfig.ResolveRef(this);
        LevelConfig.ResolveRef(this);
        EntityConfig.ResolveRef(this);
        EnemyConfig.ResolveRef(this);
    }
}

}
