
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Entity
{
public sealed partial class EntityCfg : Luban.BeanBase
{
    public EntityCfg(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
    }

    public static EntityCfg DeserializeEntityCfg(JSONNode _buf)
    {
        return new Entity.EntityCfg(_buf);
    }

    /// <summary>
    /// 实体id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 实体名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 立绘
    /// </summary>
    public readonly string Icon;
   
    public const int __ID__ = -1578315466;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "icon:" + Icon + ","
        + "}";
    }
}
}

