
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Entity
{
/// <summary>
/// 实体表
/// </summary>
public partial class EntityConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Entity.EntityCfg> _dataMap;
    private readonly System.Collections.Generic.List<Entity.EntityCfg> _dataList;
    
    public EntityConfig(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, Entity.EntityCfg>(count);
        _dataList = new System.Collections.Generic.List<Entity.EntityCfg>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Entity.EntityCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.Entity.EntityCfg.DeserializeEntityCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Entity.EntityCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<Entity.EntityCfg> DataList => _dataList;

    public Entity.EntityCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Entity.EntityCfg Get(int key) => _dataMap[key];
    public Entity.EntityCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

