
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Level
{ 
    public enum E_LevelType
    {
        /// <summary>
        /// 战斗
        /// </summary>
        Fight = 1,
    }

} 

