
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Level
{
public sealed partial class LevelCfg : Luban.BeanBase
{
    public LevelCfg(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["level_type"].IsNumber) { throw new SerializationException(); }  LevelType = (Level.E_LevelType)_buf["level_type"].AsInt; }
    }

    public static LevelCfg DeserializeLevelCfg(JSONNode _buf)
    {
        return new Level.LevelCfg(_buf);
    }

    /// <summary>
    /// 关卡id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 关卡类型
    /// </summary>
    public readonly Level.E_LevelType LevelType;
   
    public const int __ID__ = -1447442006;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "levelType:" + LevelType + ","
        + "}";
    }
}
}

