
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Level
{
/// <summary>
/// 关卡表
/// </summary>
public partial class LevelConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Level.LevelCfg> _dataMap;
    private readonly System.Collections.Generic.List<Level.LevelCfg> _dataList;
    
    public LevelConfig(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, Level.LevelCfg>(count);
        _dataList = new System.Collections.Generic.List<Level.LevelCfg>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Level.LevelCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.Level.LevelCfg.DeserializeLevelCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Level.LevelCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<Level.LevelCfg> DataList => _dataList;

    public Level.LevelCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Level.LevelCfg Get(int key) => _dataMap[key];
    public Level.LevelCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

