
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Audio
{
public sealed partial class AudioCfg : Luban.BeanBase
{
    public AudioCfg(JSONNode _buf) 
    {
        { if(!_buf["key"].IsString) { throw new SerializationException(); }  Key = _buf["key"]; }
        { if(!_buf["path"].IsString) { throw new SerializationException(); }  Path = _buf["path"]; }
        { if(!_buf["volume"].IsNumber) { throw new SerializationException(); }  Volume = _buf["volume"]; }
    }

    public static AudioCfg DeserializeAudioCfg(JSONNode _buf)
    {
        return new Audio.AudioCfg(_buf);
    }

    /// <summary>
    /// AudioKey
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// 路径
    /// </summary>
    public readonly string Path;
    /// <summary>
    /// 音量
    /// </summary>
    public readonly float Volume;
   
    public const int __ID__ = 1015892998;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "path:" + Path + ","
        + "volume:" + Volume + ","
        + "}";
    }
}
}

