
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Audio
{
/// <summary>
/// 音效表
/// </summary>
public partial class AudioConfig
{
    private readonly System.Collections.Generic.Dictionary<string, Audio.AudioCfg> _dataMap;
    private readonly System.Collections.Generic.List<Audio.AudioCfg> _dataList;
    
    public AudioConfig(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, Audio.AudioCfg>(count);
        _dataList = new System.Collections.Generic.List<Audio.AudioCfg>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Audio.AudioCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.Audio.AudioCfg.DeserializeAudioCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, Audio.AudioCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<Audio.AudioCfg> DataList => _dataList;

    public Audio.AudioCfg GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Audio.AudioCfg Get(string key) => _dataMap[key];
    public Audio.AudioCfg this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

