
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Condition
{ 
    public enum E_ConditionType
    {
        /// <summary>
        /// 无效
        /// </summary>
        None = -1,
        /// <summary>
        /// (通用)失败
        /// </summary>
        Fail = 0,
        /// <summary>
        /// (通用)成功
        /// </summary>
        Success = 1,
        /// <summary>
        /// 参数1：玩家等级
        /// </summary>
        PlayerLevel = 2,
        /// <summary>
        /// (框架)复合
        /// </summary>
        Composite = 99999999,
    }

} 

